### ISSUE TITLE
Extending random data generator to PyTorch Dataset/DataLoader classes

### ISSUE THREAD

**Issue by jacopoabramo** [softmatterlab/DeepTrack2#141]
Greetings,

I'm currently trying to implement a CNN using PyTorch. Previously I attempted to implement my own training loop and I managed to use the DeepTrack data pipeline generator with the model and support for GPU processing (see #133). Now I'm taking it up a notch.

I'm currently using [PyTorch Lightning](https://github.com/Lightning-AI/lightning) to implement a more reproducible environment for my model's training, since it offers an interface not so different from Keras in terms of APIs and callbacks. The only issue I have with this is that it does not allow me to use the data generator as a context manager, hence for each dataset I use, I need to manually create the data from the pipeline. So for example a dataset compatible with this package would be:

```python
from torch.utils.data import Dataset, DataLoader
from torchvision.transforms.functional import to_tensor

class DeeptrackDataset(Dataset):
    def __init__(self, data_pipeline: dt.Feature, dataset_size: int) -> None:
        dataset = [data_pipeline.update().resolve() for _ in range(dataset_size)]
        labels = [get_label(image) for image in dataset]
        self.dataset = torch.stack([to_tensor(np.array(image)).float().to(device) for image in dataset])
        self.labels = torch.from_numpy(np.array(labels)).float().to(device)
    
    def __len__(self):
        return len(self.dataset)
    
    def __getitem__(self, idx):
        return (self.dataset[idx], self.labels[idx])
```

This is due to the fact that PyTorch `DataLoader` class needs a `Dataset` object from which to get the items from, as you already know.
For completion, the Lightning package uses  uses a data module class which constructs `DataLoader` objects which are used depending on the training loop step. So for example I implemented something like this:

```python
import pytorch_lightning as pl

class DeeptrackDataModule(pl.LightningDataModule):
    def __init__(self, data_pipeline: dt.Feature,
                batch_size: int,
                training_size: int = 128,
                validation_size: int = 64,
                test_size: int = 32,
                predict_size: int = 16) -> None:
        super().__init__()
        self.batch_size = batch_size
        self.training_dataset = DeeptrackDataset(data_pipeline, training_size)
        self.validation_dataset = DeeptrackDataset(data_pipeline, validation_size)
        self.test_dataset = DeeptrackDataset(data_pipeline, test_size)
        self.predict_dataset = DeeptrackDataset(data_pipeline, predict_size)
    
    def train_dataloader(self):
        return DataLoader(self.training_dataset, batch_size=self.batch_size)

    def val_dataloader(self):
        return DataLoader(self.validation_dataset, batch_size=max(self.batch_size * 4, len(self.validation_dataset)))

    def test_dataloader(self):
        return DataLoader(self.test_dataset, batch_size=max(self.batch_size * 4, len(self.test_dataset)))

    def predict_dataloader(self):
        return DataLoader(self.predict_dataset, batch_size=max(self.batch_size * 4, len(self.predict_dataset)))

data_module = DeeptrackDataModule(data_pipeline, batch_size)
```

So what happens is that for training, the dataset will always be the same. While what I would like is to still have the possibility to randomly generate data from the pipeline.
Is there any chance to extend the random generation to these objects somehow?

**Comment by BenjaminMidtvedt** [comment]
To clarify, when and how would you like the data to be generated? A new complete new set of training data every epoch?

**Comment by jacopoabramo** [comment]
Hi @BenjaminMidtvedt ,  thanks for looking into this. A new complete set at every epoch would be great, yes. I though about using the `on_train_epoch_end` provided by te `LightningModule` class. The only problem is that by manually refreshing the data in this way would become time consuming in case that for example the size of my training set is particurlary large. For example to create 2048 data points it requires at least between 2-3 minutes. I usually train for 100+ epochs, so this delay stacks up and becomes quite annoying.

**Comment by jacopoabramo** [comment]
Hi @BenjaminMidtvedt , I'll give it a go tomorrow and report if it works or not.

**Comment by jacopoabramo** [comment]
Here I am.

So the generator seems to be working properly. I have issues using the `num_workers` parameter but this apparently has been a problem that a lot of people have faced. Torch has its own [implementation](https://pytorch.org/docs/stable/notes/multiprocessing.html#cuda-in-multiprocessing) of the `multiprocessing`, which should be used instead. I did not investigate how this should be actually replaced when using torch dataloaders, but it's unrelated to the issue anyway.

I did get the following exception though: AttributeError: `'DynamicDeeptrackDataset' object has no attribute 'replace_probability'`, which makes sense as the `replace_probability` field is only referenced at the start of `_maybe_replace_index`. Could you elaborate on what this parameter is and what should it be used for?

**Comment by BenjaminMidtvedt** [comment]
@jacopoabramo 

My bad! Poor copy-paste skills. 

```
def __init__(self, data_pipeline: dt.Feature, dataset_size: int, replace_probability: float) -> None:
    self.replace_probability = replace_probability
    ...
```
   
Should be it.

It is a coin toss representing whether a specific sample in the dataset should be replaced or not when accessed. This can be a middle-ground between completely replacing the dataset each epoch (very time-consuming), and not replacing it at all (limits the data the network sees).

**Comment by jacopoabramo** [comment]
@BenjaminMidtvedt 

Cool, got it. At any rate this works perfectly for my needs. I'll close the issue.
