### ISSUE TITLE
Documentation link dead

### ISSUE THREAD

**Issue by dcnieho** [softmatterlab/DeepTrack2#153]
The README in several places links to https://softmatterlab.github.io/DeepTrack-2.0/deeptrack.html. However, thats a 404. Could you put the documentation up somewhere again?

**Comment by dcnieho** [comment]
The correct link is: https://softmatterlab.github.io/DeepTrack2/

**Comment by BenjaminMidtvedt** [comment]
Thanks for notifying us! We'll update the links to match.
