### ISSUE TITLE
Bug?: Pip install fails due to scikit-image

### ISSUE THREAD

**Issue by elindgren** [softmatterlab/DeepTrack2#154]
`pip install deeptrack` in a fresh virtual environment fails when building `scikit-image`. I've tried installing `numpy` before `deeptrack` as per the installation instructions, but that still fails. I've tried with several different `numpy` versions:

## `numpy==1.23.5`
Complains about incompatible `numpy` version:

```bash
`numpy.distutils` is deprecated since NumPy 1.23.0, as a result
of the deprecation of `distutils` itself. It will be removed for
Python >= 3.12. For older Python versions it will remain present.
It is recommended to use `setuptools < 60.0` for those Python versions.
For more details, see:
  https://numpy.org/devdocs/reference/distutils_status_migration.html
```
## `numpy==1.22.4`

```bash
      INFO:
      ########### EXT COMPILER OPTIMIZATION ###########
      INFO: Platform      :
        Architecture: x64
        Compiler    : gcc
      
      CPU baseline  :
        Requested   : 'min'
        Enabled     : SSE SSE2 SSE3
        Flags       : -msse -msse2 -msse3
        Extra checks: none
      
      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_KNM AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
        Generated   : none
      INFO: CCompilerOpt.cache_flush[825] : write cache to path -> /tmp/pip-install-96oous6u/scikit-image_c108e0b2a1044b02a6d3d13cde66a5b6/build/temp.linux-x86_64-3.10/ccompiler_opt_cache_ext.py
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> scikit-image
```

Fails with esoteric error during compilation

## Installing `scikit-image` manually

If I install `scikit-image` manually it installs version `0.19.3` which works fine regardless of `numpy` version, but when I install `deeptrack` it instead tries to install version `0.17.2`. `scikit-image` isn't pinned in your `requirements.txt`, perhaps there is a peer dependency that limits the version?

## Environment

OS: Ubuntu 22.04 LTS
Python version: 3.10
Pip: 22.0.2
Python virutal environment (`venv`)

**Comment by BenjaminMidtvedt** [comment]
This is a known and reoccurring issue with scikit-image. The problem is that some other dependency of deeptrack locks the scikit image version to a version that was never released for your OS and python version. This means that wheel tries to build it from source instead. Ususally this works, but for some reason, it never works for scikit-image.

I thought I had fixed this issue already, but it turns out that pydeepimagej is the actual culprit. It is not a necessary dependency for deeptrack. I'll do a patch release removing it.

In the meantime, you can do

`pip install --no-deps deeptrack`

to bypass the issue. You can then run `pip check` to find what dependencies are missing. Install all of them except pydeepimagej.

**Comment by elindgren** [comment]
> This is a known and reoccurring issue with scikit-image. The problem is that some other dependency of deeptrack locks the scikit image version to a version that was never released for your OS and python version. This means that wheel tries to build it from source instead. Usually this works, but for some reason, it never works for scikit-image.
> 
> I thought I had already fixed this issue, but it turns out that pydeepimagej is the culprit. It is not a necessary dependency for deeptrack. I'll do a patch release removing it.
> 
> In the meantime, you can do
> 
> `pip install --no-deps deeptrack`
> 
> to bypass the issue. You can then run `pip check` to find the missing dependencies. Install all of them except pydeepimagej.

Thanks! Your workaround worked for me.
