### ISSUE TITLE
Saving & loading models 

### ISSUE THREAD

**Issue by seanbyrne226** [softmatterlab/DeepTrack2#158]
Hi there,

 I am trying to save my trained model using the standard keras procedure e.g `model.save ('my_model') / reconstructed_model = keras.models.load_model("my_model")`  However, this causes the following error when `WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op`

I am wondering what is the correct procedure to save and load deeptrack models?

**Comment by BenjaminMidtvedt** [comment]
If you only want to do inference (no further training), you can safely ignore the warnings. Alternatively, you can try saving the models as hdf5 files instead.

If you want to keep training the network, you can either swap to `load_weights` or, again, save as hdf5.

Let me know if this works for you!

**Comment by seanbyrne226** [comment]
It works thanks :)
