### ISSUE TITLE
Error in "cell migration analysis"_module 5 "Evaluating the network"

### ISSUE THREAD

**Issue by leileiChenplus** [softmatterlab/DeepTrack2#175]
Hi!

There seems to be an issue in the example Particle tracing-[Training MAGIK to trace migrating cells](https://colab.research.google.com/github/softmatterlab/DeepTrack-2.0/blob/develop/examples/MAGIK/cell_migration_analysis.ipynb).
In module of Evaluating the network_**gnns.get_predictions**, we confront an error as below:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[13], line 1
----> 1 pred, gt, scores, graph = dt.models.gnns.get_predictions(
      2     test_nodesdf, ["centroid"], model, variables
      3 )

TypeError: get_predictions() takes 3 positional arguments but 4 were given

Have you noticed this? If yes, is there any solution for this problem?

**Comment by JesusPinedaC** [comment]
Hello!

Thanks for reporting this issue. We have updated the example to fix the error.

Feel free to contact us again if the problem persists!
