### ISSUE TITLE
Training a model from multiple images

### ISSUE THREAD

**Issue by gournge** [softmatterlab/DeepTrack2#186]
Hi! 
I am trying to train LodeSTAR on multiple images - they are all small snapshots of particles of slightly different shapes and sizes.
Unfortunately I only noticed in the provided examples that the model was trained on a dataset generated from one image only. 

Perhaps there is way to somehow utilize the `SequentialGenerator`?

Thanks in advance :)

**Comment by BenjaminMidtvedt** [comment]
Hi! No problem, to train on multiple examples, simply do:

```python
import random
my_crops = [crop_1, crop_2, ...]

random_crop = dt.Value(lambda: random.choice(my_crops))

model = dt.models.LodeSTAR()
model.fit(random_crop, batch_size=8, epochs=50, steps_per_epoch=100)
```
